# Generated by Django 5.2.4 on 2025-07-21 03:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuerpo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Cuerpo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('imagen', models.ImageField(default='cuerpos/default.png', upload_to='cuerpos/', verbose_name='Imagen del Cuerpo')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Producto')),
                ('descripcion', models.TextField(verbose_name='Descripción Detallada')),
                ('cantidad', models.PositiveIntegerField(default=0, verbose_name='Cantidad en Stock')),
                ('imagen', models.ImageField(default='productos/default.png', upload_to='productos/', verbose_name='Imagen del Producto')),
                ('ubicacion', models.CharField(blank=True, max_length=150, null=True, verbose_name='Ubicación Física')),
                ('estado', models.CharField(choices=[('Nuevo', 'Nuevo'), ('Bueno', 'Bueno'), ('Usado', 'Usado'), ('Reparación', 'Requiere Reparación')], default='Bueno', max_length=20, verbose_name='Estado del Producto')),
                ('fecha_adquisicion', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Adquisición')),
                ('cuerpo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='inventario.cuerpo', verbose_name='Cuerpo al que pertenece')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('Entrada', 'Entrada'), ('Salida', 'Salida')], max_length=10)),
                ('cantidad', models.PositiveIntegerField()),
                ('motivo', models.CharField(max_length=255, verbose_name='Motivo del movimiento')),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventario.producto')),
            ],
        ),
    ]
