# Generated by Django 5.2.4 on 2025-07-21 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(default='Sin Descripción', null=True, verbose_name='Descripción Detallada'),
        ),
    ]
