# Generated by Django 5.2.4 on 2025-07-21 05:33

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_producto_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuerpo',
            name='imagen',
            field=cloudinary.models.CloudinaryField(default='v1721544336/default_cuerpo_wimnux.png', max_length=255, verbose_name='Imagen del Cuerpo'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=cloudinary.models.CloudinaryField(default='v1721544336/default_producto_yq1xou.png', max_length=255, verbose_name='Imagen del Producto'),
        ),
    ]
