# Generated by Django 5.2.4 on 2025-07-21 07:25

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_cuerpo_imagen_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuerpo',
            name='imagen',
            field=cloudinary.models.CloudinaryField(default='default_ajqgij', max_length=255, verbose_name='Imagen del Cuerpo'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=cloudinary.models.CloudinaryField(default='default_ajqgij', max_length=255, verbose_name='Imagen del Producto'),
        ),
    ]
